### ISSUE TITLE
Please update to 1.4.0

### ISSUE THREAD

**Issue by popey** [snapcrafters/ghost-desktop#3]
New release is available since 14th Sept.

**Comment by popey** [comment]
Looks like upstream didn't put out a deb which we currently consume.

**Comment by popey** [comment]
Filed issue upstream for missing deb https://github.com/TryGhost/Ghost-Desktop/issues/296

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/ghost-desktop/commit/74418cb54a1aa5141741fb9b0ef1eb44cca12263
