### ISSUE TITLE
no access to gnome-keyring?

### ISSUE THREAD

**Issue by mainmachine** [snapcrafters/ghost-desktop#9]
Version 1.7.0 on Ubuntu 18.04 running in the Cinnamon desktop. Looks like the snap is being denied access to the gnome-keyring:

`
Uncaught (in promise) Error: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.446" (uid=1000 pid=19795 comm="/snap/ghost-desktop/71/usr/lib/Ghost/Ghost --type=" label="snap.ghost-desktop.ghost-desktop (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.11" (uid=1000 pid=4698 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")
`
Another fellow is using "--devmode" as a workaround:

[http://smac.io/ghost-desktop-issue/](http://smac.io/ghost-desktop-issue/)

...and I suspect running with classic confinement might work too.

**Comment by mainmachine** [comment]
Maybe just a guess, but does this snap need to be able to connect to the password-manager-service interface?

**Comment by ghost** [comment]
Can you rebuild with the password-manager-service interface and see if that makes a difference?
https://forum.snapcraft.io/t/the-password-manager-service-interface/7899

**Comment by mainmachine** [comment]
I will try. Never built a snap before so wish me luck :)

**Comment by mainmachine** [comment]
So adding password-manager-service does indeed fix this!

I also learned that you need to build snaps on 16.04 presently, and that "snap try prime" does not necessarily work even if the build was successful...

I did need to manually run 'sudo snap connect ghost-desktop:password-manager-service' manually, so I suspect there is some nuance to the snapcraft.yaml that I am missing.

Shall I fork and submit a PR?

**Comment by mainmachine** [comment]
submitted PR #10
